name: Puppeteer and lighthouse

on:
  workflow_run:
    workflows: ["Deploy Next.js site to Pages"]  # Change to the name of the workflow you want to depend on
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run the script
        run: node scripts/main.mjs

      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: output-artifacts
          path: auto_* 